version: '3.8'

services:
  api:
    container_name: api
    image: nardeen2/api:1.0
    #image: nardeen2/aswaneya_api:1.0
    command: uvicorn app.main:app --host 0.0.0.0
    #build:
      #context: .
      #dockerfile: Dockerfile
    #image: nardeen2/fastapi_app:1.0.0
    #image: nardeen2/fastapi_app:1.0.0
    ports:
      - 8000:8000
    restart: always
    environment:
      - DB_URL=postgresql://postgres:admin@192.168.0.3:5432/fastapi_database
      #- DB_URL=postgresql://postgres:admin@localhost:5432/fastapi_database
    #depends_on:
     # - fastapi_db
    networks:
      app_net:
        ipv4_address: 192.168.0.4

  
  DB:
    container_name: DB
    #image: postgres:alpine
    image: nardeen2/db:1.0
    #image: aswaneyamomkenapi:latest
    #hostname: localhost
    #build:
     # context: .
      #dockerfile: postgres.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= admin
      - PGDATA= /var/lib/postgresql/data
      #- DB_URL=postgresql://postgres:admin@127.0.0.1:5432/fastapi_database
      
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    ports:
      - 5432:5432
    volumes:
      - ./data/DB_data:/var/lib/postgresql/data
      #- C:\postgres_container_data:/var/lib/postgresql/data
      #- postgres-data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    build:
      context: .
    restart: always
    #volumes:
     # - ./data/pg-data:
    
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      # PGADMIN_LISTEN_PORT = 80
      #- DB_URL=default://postgres:admin@127.0.0.3:5432/fastapi_database
    ports:
      - 5050:80

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
